name: Update Hosts

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge hosts lists
        run: |
          curl -sSL https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/tif.txt >> hosts.txt
          curl -sSL https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/urlshortener.txt >> hosts.txt
          curl -sSL https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/tld.txt >> hosts.txt
          curl -sSL https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/fake.txt >> hosts.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hosts
          path: hosts.txt
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add hosts.txt
          git commit -m "Update hosts" || echo "No changes"
          git push
